name: Craftmen
version: 1.0
main: com.tommustbe12.craftmen.Craftmen
api-version: 1.20
commands:
  setuparena:
    description: Create a new arena
    usage: /setuparena <name>
    permission: craftmen.admin
  checkstatus:
    description: Debug only! Checks your player state
    usage: /checkstatus
  hub:
    description: Go to the server hub
    usage: /hub
  duel:
    description: Duel a player in Craftmen
    usage: /duel <name>
  accept:
    description: Accept a duel request
    usage: /accept <name>
  leavequeue:
    aliases: lq
    description: Leave the queue
    usage: /leavequeue
  stat:
    aliases: s
    description: Change the stats of a player
    usage: /stat <player> <wins|losses|deaths> <add|sub|reset> [amount]
    permission: craftmen.admin
  forfeit:
    aliases: f
    description: Forfeit the match you are in
    usage: /forfeit
permissions:
  craftmen.admin:
    default: op