name: Craftmen
version: 1.0
main: com.tommustbe12.craftmen.Craftmen
api-version: 1.20
commands:
  setuparena:
    description: Create a new arena
    usage: /setuparena <name>
    default: op
  checkstatus:
    description: Debug only! Checks your player state
    usage: /checkstatus
  hub:
    description: Go to the server hub
    usage: /hub
  duel:
    description: Duel a player in Craftmen
    usage: /duel <name>
  accept:
    description: Accept a duel request
    usage: /accept <name>